apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080  # The port on which the back is available to the front
      targetPort: 8080  # Port inside a container
  type: ClusterIP
